//CommonJS, every file is module (by default)
//Modules - Encapsulated Code (only share minium)
const names = require('./4_names')
const sayHi = require('./5_utilis')
const data = require('./6_alternative-flavor')
require('./7_mind_grenade')
sayHi('Susan')
sayHi(names.john)
sayHi(names.peter)